### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by northcreativedesign** [northcreativedesign/Pacific-Printing#1]
- [ ] Get Mailchimp Access From Dan

- [ ] Tighten Up Text
- [ ] Update Site Chart
- [ ] Fix Upload File Styling
- [ ] Make Selection Boxes Styled Like Design
- [ ] Pantone Link

- [ ] Finish Responsiveness for site wide.
